# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 The Khatu Family Trust
# File: example/pubspec.yaml
# File Version: 1.0.0

name: catu_framework_example
description: Example app for catu_framework
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  catu_framework:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
